Drogueria/Models/ClientesModel.cs
namespace Drogueria.Models
{
    public class ClientesModel
    {
        public int id_cliente { get; set; }

        public string? Nombre_Cliente { get; set; }

        public int nit_cliente { get; set; }

        public string? Direccion { get; set; }

        public string? Telefono { get; set; }
    }
}

Drogueria/Models/ErrorViewModel.cs
namespace Drogueria.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Drogueria/Models/PedidosModel.cs
namespace Drogueria.Models
{
    public class PedidosModel
    {
        public int id_pedido { get; set; }

        public int id_producto { get; set; }

        public int cantidad { get; set; }

        public string? desc_producto { get; set; }

        public string? tipo_producto { get; set; }

        public int stock_bodega { get; set; }


    }
}

Drogueria/Models/ProductosModel.cs
namespace Drogueria.Models
{
    public class ProductosModel
    {
        public int id_producto { get; set; }

        public string? desc_producto { get; set; }

        public string? tipo_producto { get; set; }

        public decimal precio { get; set; }

        public int stock_bodega { get; set; }

        public int stock_minimo { get; set; }
    }
}

Drogueria/Models/VentasModel.cs
namespace Drogueria.Models
{
    public class VentasModel
    {

        public int id_venta { get; set; }

        public int id_cliente { get; set; }

        public int id_producto { get; set; }

        public int cantidad { get; set; }

        public int total_venta { get; set; }

        public string? Nombre_Cliente { get; set; }

        public int nit_cliente { get; set; }

        public string? Direccion { get; set; }

        public string? Telefono { get; set; }

        public string? desc_producto { get; set; }

        public string? tipo_producto { get; set; }

        public int precio { get; set; }

        public int stock_bodega { get; set; }

        public int stock_minimo { get; set; }

        public string? total_ventas_drogueria { get; set; }

        public string? productos_mas_vendido { get; set; }

        public string? productos_menos_vendido { get; set; }
    }
}

Drogueria/Controllers/ClienteController.cs
using Drogueria.Data;
using Drogueria.Models;
using Microsoft.AspNetCore.Mvc;

namespace Drogueria.Controllers
{
    public class ClienteController : Controller
    {
        ClientesData _ClientesData = new ClientesData();

        public IActionResult ListaClientes()
        {
            var obj_Lista = _ClientesData.ListaClientes();
            return View(obj_Lista);
        }

        public IActionResult CrearCliente()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CrearCliente(ClientesModel obj_Cliente)
        {
            var respuesta = _ClientesData.CrearCliente(obj_Cliente);

            if (respuesta)
            {
                return RedirectToAction("ListaClientes");
            }
            else
            {
                return View();
            }

        }
    }
}

Drogueria/Controllers/HomeController.cs
using Drogueria.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Drogueria.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Drogueria/Controllers/PedidoController.cs
using Drogueria.Data;
using Drogueria.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections;

namespace Drogueria.Controllers
{
    public class PedidoController : Controller
    {
        PedidosData _PedidosData = new PedidosData();

        public IActionResult ListaPedidos()
        {
            var obj_Lista = _PedidosData.ListaPedidos();
            return View(obj_Lista);
        }

        public IActionResult CrearPedido()
        {
            ViewData["combo"] = new SelectList(GetProducto(), "id_producto", "desc_producto");
            return View();
        }

        private IEnumerable GetProducto()
        {
            var obj_Lista = _PedidosData.ListaProductos();
            return obj_Lista;
        }

        [HttpPost]
        public IActionResult CrearPedido(PedidosModel obj_Pedido)
        {
            var respuesta = _PedidosData.CrearPedido(obj_Pedido);

            if (respuesta)
            {
                return RedirectToAction("ListaPedidos");
            }
            else
            {
                return View();
            }

        }
    }
}

Drogueria/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;

using Drogueria.Data;
using Drogueria.Models;

namespace Drogueria.Controllers
{
    public class ProductoController : Controller
    {
        ProductosData _ProductosData = new ProductosData();

        public IActionResult ListaProductos()
        {
            var obj_Lista = _ProductosData.ListaProductos();
            return View(obj_Lista);
        }

        public IActionResult CrearProducto()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CrearProducto(ProductosModel obj_Producto)
        {
            var respuesta = _ProductosData.CrearProducto(obj_Producto);

            if (respuesta)
            {
                return RedirectToAction("ListaProductos");
            }
            else
            {
                return View();
            }
            
        }
    }
}

Drogueria/Controllers/VentaController.cs
using Drogueria.Data;
using Drogueria.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections;

namespace Drogueria.Controllers
{
    public class VentaController : Controller
    {
        VentasData _VentasData = new VentasData();
        public IActionResult ListaVentas()
        {
            var obj_Lista = _VentasData.ListaVentas();
            return View(obj_Lista);
        }

        public IActionResult CrearVenta()
        {
            ViewData["combo"] = new SelectList(GetProducto(), "id_producto", "desc_producto");
            ViewData["combo2"] = new SelectList(GetClientes(), "id_cliente", "Nombre_Cliente");
            return View();
        }

        private IEnumerable GetProducto()
        {
            var obj_Lista = _VentasData.ListaProductos();
            return obj_Lista;
        }

        private IEnumerable GetClientes()
        {
            var obj_Lista = _VentasData.ListaClientes();
            return obj_Lista;
        }


        [HttpPost]
        public IActionResult CrearVenta(VentasModel obj_Venta)
        {
            var respuesta = _VentasData.CrearVenta(obj_Venta);

            if (respuesta)
            {
                return RedirectToAction("ListaVentas");
            }
            else
            {
                return View();
            }

        }

        public IActionResult TotalVentas()
        {
            var obj_Venta = _VentasData.TotalVentas();
            return View(obj_Venta);
        }


    }
}

Drogueria/Views/Cliente/CrearCliente.cshtml
@model ClientesModel
@{
    ViewData["Title"] = "CrearCliente";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card">
    <div class="card-header">
        Crear Cliente
    </div>
    <div class="card-body">
        <form asp-action="CrearCliente" asp-controller="Cliente" method="post">
            <div class="mb-3">
                <label class="form-label">Nombre:</label>
                <input asp-for="Nombre_Cliente" class="form-control" type="text" placeholder="Nombre Cliente" aria-label="default input example">
            </div>
            <div class="mb-3">
                <label class="form-label">Nit:</label>
                <input asp-for="nit_cliente" class="form-control" type="text" placeholder="Nit" aria-label="default input example">
            </div>
            <div class="mb-3">
                <label class="form-label">Direccion:</label>
                <input asp-for="Direccion" class="form-control" type="text" placeholder="Direccion" aria-label="default input example">
            </div>
            <div class="mb-3">
                <label class="form-label">Telefono:</label>
                <input asp-for="Telefono" class="form-control" type="text" placeholder="Telefono" aria-label="default input example">
            </div>
            <button type="submit" class="btn btn-primary">Crear</button>
        </form>
    </div>
</div>

Drogueria/Views/Cliente/ListaClientes.cshtml
@model List<ClientesModel>

@{
    ViewData["Title"] = "ListaClientes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Clientes
    </div>
    <div class="card-body">
        <a asp-action="CrearCliente" asp-controller="Cliente" class="btn btn-success">Crear Cliente</a>
        <hr />
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nombre Cliente</th>
                    <th scope="col">Nit Cliente</th>
                    <th scope="col">Direccion</th>
                    <th scope="col">Telefono</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th scope="row">@item.id_cliente</th>
                        <td>@item.Nombre_Cliente</td>
                        <td>@item.nit_cliente</td>
                        <td>@item.Direccion</td>
                        <td>@item.Telefono</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Drogueria/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido al sistema de control Drogueria</h1>
</div>

Drogueria/Views/Pedido/CrearPedido.cshtml
@model PedidosModel
@{
    ViewData["Title"] = "CrearPedido";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Crear Cliente
    </div>
    <div class="card-body">
        <form asp-action="CrearPedido" asp-controller="Pedido" method="post">
            <div class="mb-3">
                <label class="form-label">Producto a Solicitar:</label>
                <select asp-items="@ViewData["combo"] as SelectList" asp-for="id_producto" ></select>
            </div>
            <div class="mb-3">
                <label class="form-label">Cantidad:</label>
                <input asp-for="cantidad" class="form-control" type="text" placeholder="Cantidad a Solicitar" aria-label="default input example">
            </div>
            <button type="submit" class="btn btn-primary">Crear</button>
        </form>
    </div>
</div>

Drogueria/Views/Pedido/ListaPedidos.cshtml
@model List<PedidosModel>
@{
    ViewData["Title"] = "ListaPedidos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="card">
    <div class="card-header">
        Historial Pedidos Solicitados a Laboratorio
    </div>
    <div class="card-body">
        <a asp-action="CrearPedido" asp-controller="Pedido" class="btn btn-success">Crear Pedido</a>
        <hr />
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Producto</th>
                    <th scope="col">Tipo Producto</th>
                    <th scope="col">Cantidad Solicitada</th>
                    <th scope="col">Stock Actual En Bodega</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th scope="row">@item.id_pedido</th>
                        <td>@item.desc_producto</td>
                        <td>@item.tipo_producto</td>
                        <td>@item.cantidad</td>
                        <td>@item.stock_bodega</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Drogueria/Views/Producto/CrearProducto.cshtml
@model ProductosModel
@{
    ViewData["Title"] = "CrearProducto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Crear Producto
    </div>
    <div class="card-body">
    <form asp-action="CrearProducto" asp-controller="Producto" method="post">
        <div class="mb-3">
            <label class="form-label">Producto:</label>
            <input asp-for="desc_producto" class="form-control" type="text" placeholder="Ingrese Descripcion Producto" aria-label="default input example">
        </div>
        <div class="mb-3">
            <label class="form-label">Tipo:</label>
            <input asp-for="tipo_producto" class="form-control" type="text" placeholder="Ingrese Tipo Producto" aria-label="default input example">
        </div>
        <div class="input-group mb-3">
            <label class="form-label">Precio:</label><br />
            <span class="input-group-text">$</span>
            <input asp-for="precio" type="text" class="form-control" placeholder="Ingrese Precio Producto">
            <span class="input-group-text">.00</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Stock Bodega:</label>
            <input asp-for="stock_bodega" class="form-control" type="text" placeholder="Ingrese Stock Bodega" aria-label="default input example">
        </div>
        <div class="mb-3">
            <label class="form-label">Stock Minimo:</label>
                <input asp-for="stock_minimo" class="form-control" type="text" placeholder="Ingrese Stock Minimo" aria-label="default input example">
        </div>
      <button type="submit" class="btn btn-primary">Crear</button>
    </form>
    </div>
</div>

Drogueria/Views/Producto/ListaProductos.cshtml
@model List<ProductosModel>

@{
    ViewData["Title"] = "ListaProductos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Productos
    </div>
    <div class="card-body">
        <a asp-action="CrearProducto" asp-controller="Producto" class="btn btn-success">Crear Producto</a>
        <hr />
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Producto</th>
                    <th scope="col">Tipo</th>
                    <th scope="col">Precio $</th>
                    <th scope="col">Stock Bodega</th>
                    <th scope="col">Stock Minimo</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model)
                {
                    <tr>
                        <th scope="row">@item.id_producto</th>
                        <td>@item.desc_producto</td>
                        <td>@item.tipo_producto</td>
                        <td>@item.precio</td>
                        <td>@item.stock_bodega</td>
                        <td>@item.stock_minimo</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Drogueria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Drogueria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Drogueria.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Drogueria</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Ventas</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Venta" asp-action="CrearVenta">Nueva Venta</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Venta" asp-action="ListaVentas">Historial Ventas</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Venta" asp-action="TotalVentas">Informacion Adicional de Ventas</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Pedidos</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Pedido" asp-action="CrearPedido">Crear Pedido</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Pedido" asp-action="ListaPedidos">Historial Pedidos</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Clientes</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Cliente" asp-action="CrearCliente">Crear Cliente</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Cliente" asp-action="ListaClientes">Ver Clientes</a></li>
                                <li><a class="dropdown-item disabled" href="#">Consultar Cliente</a></li>
                                <li><a class="dropdown-item disabled" href="#">Editar Cliente</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Productos</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Producto" asp-action="CrearProducto">Crear Producto</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Producto" asp-action="ListaProductos">Ver Todos Los Productos</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Drogueria - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Drogueria/Views/Venta/CrearVenta.cshtml
@model VentasModel
@{
    ViewData["Title"] = "CrearVenta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="card">
    <div class="card-header">
        Crear Nueva Venta
    </div>
    <div class="card-body">
        <form asp-action="CrearVenta" asp-controller="Venta" method="post">
            <div class="mb-3">
                <label class="form-label">Producto a Vender:</label>
                <select asp-items="@ViewData["combo"] as SelectList" asp-for="id_producto"></select>
            </div>

            <div class="mb-3">
                <label class="form-label">Cliente:</label>
                <select asp-items="@ViewData["combo2"] as SelectList" asp-for="id_cliente"></select>
            </div>

            <div class="mb-3">
                <label class="form-label">Cantidad:</label>
                <input asp-for="cantidad" class="form-control" type="text" placeholder="Cantidad Productos" aria-label="default input example">
            </div>
            <button type="submit" class="btn btn-primary">Crear</button>
        </form>
    </div>
</div>

Drogueria/Views/Venta/ListaVentas.cshtml
@model List<VentasModel>
@{
    ViewData["Title"] = "ListaVentas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Historial Ventas Drogueria
    </div>
    <div class="card-body">
        <a asp-action="CrearVenta" asp-controller="Venta" class="btn btn-success">Crear Venta</a>
        <hr />
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Cliente</th>
                    <th scope="col">Nit Cliente</th>
                    <th scope="col">Producto</th>
                    <th scope="col">Tipo Producto</th>
                    <th scope="col">Total Unidades Vendido</th>
                    <th scope="col">Precio Unidad</th>
                    <th scope="col">Total Vendido</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th scope="row">@item.id_venta</th>
                        <td>@item.Nombre_Cliente</td>
                        <td>@item.nit_cliente</td>
                        <td>@item.desc_producto</td>
                        <td>@item.tipo_producto</td>
                        <td>@item.cantidad</td>
                        <td>@item.precio</td>
                        <td>@item.total_venta</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Drogueria/Views/Venta/TotalVentas.cshtml
@model VentasModel
@{
    ViewData["Title"] = "TotalVentas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card text-center">
    <div class="card-header">
        Informacion Adicional de Ventas
    </div>
    <form asp-action="TotalVentas" asp-controller="Venta" method="post">
    <div class="card-body">
        <div class="mb-3">
            <h5 class="card-title">Total de Ingresos por ventas de la Drogueria</h5>
            <input asp-for="total_ventas_drogueria" class="form-control" type="text" aria-label="default input example">
        </div>
    </div>
    <div class="card-footer text-muted">
        <div class="row">
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Producto Mas Vendido</h5>
                        <input asp-for="productos_mas_vendido" class="form-control" type="text" aria-label="default input example">
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Producto Menos Vendido</h5>
                            <input asp-for="productos_menos_vendido" class="form-control" type="text" aria-label="default input example">
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
</div>